spring:
  datasource:
    initialization-mode: always
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    #url: jdbc:postgresql://${DATABASE_HOST:localhost}/${DATABASE_NAME:template}?currentSchema=public
    url: jdbc:sqlserver://localhost:2222;databasename=java;integratedSecurity=false
    username: sa
    password: Ybrbnjc777
    #username: ${DATABASE_USER:postgres}
    #password: ${DATABASE_PASSWORD:docker}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        jdbc:
          time_zone: UTC
          batch_size: 5
        order_updates: true
        order_inserts: true

  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/master.xml
#
#  main:
#    allow-bean-definition-overriding: true